// Common GLSL definitions
// Author: Max Schwarz <max.schwarz@ais.uni-bonn.de>

// Attribute locations.
// These are kept in sync with Magnum::Shaders::Generic3D attributes.
#define POSITION_ATTRIBUTE_LOCATION 0
#define TEXTURECOORDINATES_ATTRIBUTE_LOCATION 1
#define COLOR_ATTRIBUTE_LOCATION 2
#define TANGENT_ATTRIBUTE_LOCATION 3
#define VERTEX_INDEX_ATTRIBUTE_LOCATION 4
#define NORMAL_ATTRIBUTE_LOCATION 5

// Outputs
#define COLOR_OUTPUT_ATTRIBUTE_LOCATION 0
#define OBJECT_COORDINATES_OUTPUT_ATTRIBUTE_LOCATION 1
#define CLASS_INDEX_OUTPUT_ATTRIBUTE_LOCATION 2
#define INSTANCE_INDEX_OUTPUT_ATTRIBUTE_LOCATION 3
#define NORMAL_OUTPUT_ATTRIBUTE_LOCATION 4
#define VERTEX_INDEX_OUTPUT_ATTRIBUTE_LOCATION 5
#define BARYCENTRIC_COEFFS_OUTPUT_ATTRIBUTE_LOCATION 6
#define CAM_COORDINATES_OUTPUT_ATTRIBUTE_LOCATION 7

// other stuff
#define M_PI 3.141592653589793
