
image: "xqms/pytorch:latest"

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages: [build, pages]

build:
  stage: build
  script:
    - python setup.py install
    - python setup.py bdist_wheel
    - cpp_build/tests/tests
    - python tests/test_python.py
  artifacts:
    expire_in: 1 week
    paths:
      - dist

pages:
  stage: pages
  script:
    - pip install dist/stillleben-*.whl
    - make -C doc html
    - mkdir public
    - cp -R doc/_build/html/* public/
  artifacts:
    paths:
      - public
  only:
    - master
