
image: "pytorch/pytorch:1.0.1-cuda10.0-cudnn7-devel"

variables:
  GIT_SUBMODULE_STRATEGY: recursive

build:
  before_script:
    - apt-get -y install cmake ninja-build
  script:
    - python setup.py install
