
image: "xqms/pytorch:latest"

variables:
  GIT_SUBMODULE_STRATEGY: recursive

build:
  before_script:
    - apt-get update
    - apt-get -y install cmake ninja-build
  script:
    - python setup.py install
