image: "xqms/sl_build:v1.8.1"

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages: [build, pages]

build:
  stage: build
  script:
    - export CMAKE_PREFIX_PATH=${CONDA_PREFIX:-"$(dirname $(which conda))/../"}
    - export LD_LIBRARY_PATH=${CONDA_PREFIX:-"$(dirname $(which conda))/../"}/lib:$LD_LIBRARY_PATH
    - echo "Using CMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH} and LD_LIBRARY_PATH=${LD_LIBRARY_PATH}"
    - python setup.py install
    - python setup.py bdist_wheel
    - STILLLEBEN_CUDA_DEBUG=1 python/cpp_build/RelWithDebInfo/bin/tests
    - python tests/test_python.py
    - python tests/test_grad.py
  artifacts:
    expire_in: 1 week
    paths:
      - dist

cpp_debug:
  stage: build
  script:
    - export CMAKE_PREFIX_PATH=${CONDA_PREFIX:-"$(dirname $(which conda))/../"}
    - export LD_LIBRARY_PATH=${CONDA_PREFIX:-"$(dirname $(which conda))/../"}/lib:$LD_LIBRARY_PATH
    - echo "Using CMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH} and LD_LIBRARY_PATH=${LD_LIBRARY_PATH}"
    - mkdir build_debug && cd build_debug
    - cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS=-fsanitize=address -GNinja ..
    - ninja install
    - STILLLEBEN_CUDA_DEBUG=1 ASAN_OPTIONS=alloc_dealloc_mismatch=0 LSAN_OPTIONS=suppressions=../tests/asan_suppressions.txt Debug/bin/tests

pages:
  stage: pages
  script:
    - export LD_LIBRARY_PATH=${CONDA_PREFIX:-"$(dirname $(which conda))/../"}/lib:$LD_LIBRARY_PATH
    - pip install dist/stillleben-*.whl
    - git clone --depth 1 -b quick_fixes https://github.com/xqms/m.css.git contrib/m.css
    - python contrib/m.css/documentation/python.py doc/mcss.conf.py
    - mkdir public
    - cp -R doc/output/* public/
  artifacts:
    paths:
      - public
  only:
    - master
