
image: "xqms/pytorch:latest"

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages: [build, pages]

build:
  stage: build
  before_script:
    - apt-get update
    - apt-get -y install cmake ninja-build libglvnd-dev libegl1-mesa-dev libgl1-mesa-dev libassimp-dev libbullet-dev
  script:
    - python setup.py install
    - python setup.py bdist_wheel
  artifacts:
    expire_in: 1 week
    paths:
      - dist

pages:
  stage: pages
  before_script:
    - apt-get update
    - apt-get -y install libglvnd-dev libegl1-mesa-dev libgl1-mesa-dev libassimp-dev libbullet-dev
  script:
    - conda install -y sphinx sphinx_rtd_theme
    - pip install dist/stillleben-*.whl
    - make -C doc html
    - mkdir public
    - cp -R doc/_build/html/* public/
  artifacts:
    paths:
      - public
  only:
    - master
