image: "xqms/pytorch:latest"

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages: [build, pages]

build:
  stage: build
  script:
    - export CMAKE_PREFIX_PATH=${CONDA_PREFIX:-"$(dirname $(which conda))/../"}
    - export LD_LIBRARY_PATH=${CONDA_PREFIX:-"$(dirname $(which conda))/../"}/lib:$LD_LIBRARY_PATH
    - echo "Using CMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH} and LD_LIBRARY_PATH=${LD_LIBRARY_PATH}"
    - python setup.py install
    - python setup.py bdist_wheel
    - python/cpp_build/tests/tests
    - python tests/test_python.py
    - python tests/test_grad.py
  artifacts:
    expire_in: 1 week
    paths:
      - dist

cpp_debug:
  stage: build
  script:
    - export CMAKE_PREFIX_PATH=${CONDA_PREFIX:-"$(dirname $(which conda))/../"}
    - export LD_LIBRARY_PATH=${CONDA_PREFIX:-"$(dirname $(which conda))/../"}/lib:$LD_LIBRARY_PATH
    - echo "Using CMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH} and LD_LIBRARY_PATH=${LD_LIBRARY_PATH}"
    - mkdir build_debug && cd build_debug
    - cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS=-fsanitize=address -GNinja ..
    - ninja install
    - ASAN_OPTIONS=alloc_dealloc_mismatch=0 LSAN_OPTIONS=suppressions=../tests/asan_suppressions.txt tests/tests

pages:
  stage: pages
  script:
    - pip install dist/stillleben-*.whl
    - make -C doc html
    - mkdir public
    - cp -R doc/_build/html/* public/
  artifacts:
    paths:
      - public
  only:
    - master
